### ISSUE TITLE
Nothing is enchantable

### ISSUE THREAD

**Issue by Arthree** [gniftygnome/basalt-crusher#1]
Minecraft 1.18.2
Fabric 0.13.3
Basalt Crusher 0.2.0

The documentation and patch notes say that speed varies with efficiency enchantments. However, none of the jaw liners nor the crusher itself can be enchanted with efficiency.

![image](https://user-images.githubusercontent.com/1612820/160888093-323704ef-7c7b-441c-80ca-95b91f29bb8c.png)

**Comment by gniftygnome** [comment]
Thank you for the bug report.  I previously tested to make sure the Unbreaking enchantment was applicable to jaw liners but I must confess I forgot to test the Efficiency enchantment in Survival mode.  I'll see if I can figure out what's missing there.

**Comment by gniftygnome** [comment]
I could have declared the Jaw Liners to be DIGGER tools but that just seems wrong.  Instead I've added a mixin to Minecraft's EfficiencyEnchantment.isAcceptableItem() method to override for Jaw Liners like Mojang does for Shears.  It's too bad when they added Shears they didn't stop and think it was a good time to make a generic method for doing this...
